{% set version = ARROW_VERSION %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-arrow
  version: {{ version|replace("-", "_") }}

source:
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/apache-arrow-{{ version }}.tar.gz
  sha256: 3786b3d2df954d078b3e68f98d2e5aecbaa3fa2accf075d7a3a13c187b9c5294

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-r6                       # [build_platform != target_platform]
    - r-assertthat               # [build_platform != target_platform]
    - r-bit64                    # [build_platform != target_platform]
    - r-purrr                    # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-tidyselect               # [build_platform != target_platform]
    - python 3.9                 # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('r_clang') }}  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}sed         # [win]
    - {{ posix }}coreutils   # [win]
    - {{ posix }}filesystem  # [win]
    - {{ posix }}zip         # [win]
  host:
    # Needs to be here, otherwise merge_build_host runs into issues
    - pkg-config  # [win]
    - r-base
    - arrow-cpp {{ version }}
    - r-r6
    - r-cpp11
    - r-assertthat
    - r-bit64
    - r-purrr
    - r-rlang
    - r-tidyselect
  run:
    - r-base
    - r-r6
    - r-assertthat
    - r-bit64
    - r-purrr
    - r-rlang
    - r-tidyselect

test:
  commands:
    - $R -e "library('arrow')"           # [not win]
    - "\"%R%\" -e \"library('arrow'); data(mtcars); write_parquet(mtcars, 'test.parquet')\""  # [win]

about:
  home: https://github.com/apache/arrow
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: R Integration to 'Apache' 'Arrow'.
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r
    - conda-forge/arrow-cpp
