[package]
name = "ballista-scheduler"
description = "Ballista Distributed Compute - Scheduler"
license = "Apache-2.0"
version = "0.4.2-SNAPSHOT"
homepage = "https://github.com/ballista-compute/ballista"
repository = "https://github.com/ballista-compute/ballista"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

[features]
default = ["etcd", "sled"]
etcd = ["etcd-client"]
sled = ["sled_package"]

[dependencies]
anyhow = "1"
ballista-core = { path = "../core" }
clap = "2"
configure_me = "0.4.0"
env_logger = "0.8"
etcd-client = { version = "0.6", optional = true }
futures = "0.3"
log = "0.4"
parse_arg = "0.1.3"
prost = "0.7"
rand = "0.8"
serde = {version = "1", features = ["derive"]}
sled_package = { package = "sled", version = "0.34", optional = true }
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }
tonic = "0.4"

arrow = { git = "https://github.com/apache/arrow", rev="46161d2" }
datafusion = { git = "https://github.com/apache/arrow", rev="46161d2" }

[dev-dependencies]
ballista-core = { path = "../core" }
uuid = { version = "0.8", features = ["v4"] }

[build-dependencies]
configure_me_codegen = "0.4.0"

[package.metadata.configure_me.bin]
scheduler = "scheduler_config_spec.toml"
