# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "ballista-scheduler"
description = "Ballista Distributed Compute - Scheduler"
license = "Apache-2.0"
version = "0.4.2-SNAPSHOT"
homepage = "https://github.com/apache/arrow"
repository = "https://github.com/apache/arrow"
authors = ["Apache Arrow <dev@arrow.apache.org>"]
edition = "2018"

[features]
default = ["etcd", "sled"]
etcd = ["etcd-client"]
sled = ["sled_package"]

[dependencies]
anyhow = "1"
ballista-core = { path = "../core" }
clap = "2"
configure_me = "0.4.0"
env_logger = "0.8"
etcd-client = { version = "0.6", optional = true }
futures = "0.3"
http = "0.2"
http-body = "0.4"
hyper = "0.14.4"
log = "0.4"
parse_arg = "0.1.3"
prost = "0.7"
rand = "0.8"
serde = {version = "1", features = ["derive"]}
sled_package = { package = "sled", version = "0.34", optional = true }
tokio = { version = "1.0", features = ["full"] }
tonic = "0.4"
tower = { version = "0.4" }
warp = "0.3"

arrow = { path = "../../../arrow"  }
datafusion = { path = "../../../datafusion" }

[dev-dependencies]
ballista-core = { path = "../core" }
uuid = { version = "0.8", features = ["v4"] }

[build-dependencies]
configure_me_codegen = "0.4.0"

[package.metadata.configure_me.bin]
scheduler = "scheduler_config_spec.toml"
