[package]
name = "parquet_derive"
version = "0.2.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6.10"
syn = { version = "0.15.22", features = ["full", "extra-traits"] }
parquet = { path = "../parquet" }
