# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: generic

os: osx
osx_image: xcode8.3

env:
  global:
    - PLAT=x86_64
    - TRAVIS_TAG={{ task.tag }}
    - BUILD_REF={{ arrow.head }}
    - PYARROW_VERSION={{ arrow.version }}
    - MACOSX_DEPLOYMENT_TARGET="10.9"
    - MB_PYTHON_VERSION={{ python_version }}
    - NP_BUILD_DEP="{{ numpy_build_version }}"
    - NP_TEST_DEP="{{ numpy_test_version }}"
    - PANDAS_DEP="{{ pandas_version }}"
    - PYARROW_BUILD_VERBOSE=1

before_install:
  - git clone https://github.com/matthew-brett/multibuild # TODO pin it
  - git clone -b {{ arrow.branch }} {{ arrow.remote }} arrow
  - git -C arrow checkout {{ arrow.head }}

  # Also remove artifacts that depend on Boost
  - brew uninstall boost cgal postgis sfcgal
  - brew update
  - brew upgrade cmake
  - brew install bison flex

  - export CONFIG_PATH=`pwd`/arrow/dev/tasks/python-wheels/osx-build.sh
  - source multibuild/common_utils.sh
  - source multibuild/travis_osx_steps.sh

  - before_install

install:
  - BUILD_DEPENDS="numpy==$NP_BUILD_DEP six cython"
  - TEST_DEPENDS="numpy==$NP_TEST_DEP six pandas==$PANDAS_DEP"

  - mkdir -p dist

  # multibuild's default clean_code function
  - clean_code arrow $BUILD_REF

  # the following functions are defined in osx-build.sh
  - build_wheel arrow
  - install_run arrow

  # move built wheels to a top level directory
  - mv -v arrow/python/dist/* dist/

deploy:
  provider: releases
  api_key: $CROSSBOW_GITHUB_TOKEN
  file_glob: true
  file: dist/*.whl
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    - {{ job.email }}
