sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.9   # Needed for C++11
    - g++-4.9   # Needed for C++11
    - gdb
    - ccache
    - cmake
    - valgrind
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libjemalloc-dev
    - gtk-doc-tools
    - autoconf-archive
    - libgirepository1.0-dev
services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/.conda_packages
    - $HOME/.ccache

matrix:
  fast_finish: true
  allow_failures:
  - env: ARROW_TEST_GROUP=packaging
  include:
  - compiler: gcc
    language: cpp
    os: linux
    group: deprecated
    before_script:
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"
    - $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh
    - $TRAVIS_BUILD_DIR/ci/travis_before_script_c_glib.sh
    script:
    - $TRAVIS_BUILD_DIR/ci/travis_script_cpp.sh
    - $TRAVIS_BUILD_DIR/ci/travis_script_python.sh
    - $TRAVIS_BUILD_DIR/ci/travis_script_c_glib.sh
  - compiler: clang
    osx_image: xcode6.4
    os: osx
    cache:
    addons:
    before_script:
    - $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh
    script:
    - $TRAVIS_BUILD_DIR/ci/travis_script_cpp.sh
    - $TRAVIS_BUILD_DIR/ci/travis_script_python.sh
  - language: cpp
    before_script:
    - docker pull quay.io/xhochy/arrow_manylinux1_x86_64_base:ARROW-927
    script: |
        pushd python/manylinux1
        git clone ../../ arrow
        docker build -t arrow-base-x86_64 -f Dockerfile-x86_64 .
        docker run --rm -v $PWD:/io arrow-base-x86_64 /io/build_arrow.sh
        ls -l dist/
  - language: java
    os: linux
    jdk: oraclejdk7
    script:
    - $TRAVIS_BUILD_DIR/ci/travis_script_java.sh
  - language: java
    os: linux
    env: ARROW_TEST_GROUP=integration
    jdk: oraclejdk7
    before_script:
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"
    - $TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh
    script:
    - $TRAVIS_BUILD_DIR/ci/travis_script_integration.sh

before_install:
- ulimit -c unlimited -S
- export CPP_BUILD_DIR=$TRAVIS_BUILD_DIR/cpp-build
- export ARROW_CPP_INSTALL=$TRAVIS_BUILD_DIR/cpp-install

after_script:
- rm -rf $CPP_BUILD_DIR

after_failure:
- COREFILE=$(find . -maxdepth 2 -name "core*" | head -n 1)
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

env:
  global:
  - secure: "GcrPtsKUCgNY7HKYjWlHQo8SiFrShDvdZSU8t1m1FJrE+UfK0Dgh9zXmAausM8GmhqSwkF0q4UbLQf2uCnSITWKeEPAL8Mo9eu4ib+ikJx/b3Sk81frgW5ADoHfW1Eyqd8xJNIMwMegJOtRLSDqiXh1CvMlKnY8PyTOGM2DgN9ona/v6p9OFH9Qs0JhBRVXAn0S4ztjumck8E56+01hqRfxbZ88pTfpKghBxYp9PJaMjtGdomjVWlqPaWaWJj+KptT8inV9NK+TVYKx0dXWD+S1Vgr1PytQnLdILOYV23gsOBYqn33ByF/yADl4m3hUjU/qeT0Fi7aWxmVpj+oTJISOSH5N8nIsuNH8mQk2ZzzXHfV7btFvP+cOPRczadoKkT6D6cHA8nQ7b0dphC6bl6SAeSfc/cbhRT+fYnIjg8jFXC8jlyWBr7LR6GXVpc0bND7i300ITo0FuRJhy2OxqPtGo3dKLE7eAcv78tuO0OYJ/kol1PEqFdFkbYbNVbg/cFpbGqiCXDsOtPDbAGBv69YnXdVowSxxs8cRGjSkDydv6ZSytb/Zd4lH/KAomcFNk8adx12O1Lk4sbmVav1cGig5P6OcQKS0jC5IiRb4THcQzVzAkXXbaafKm5sru/NoYxhzmkyhkOc11nTYHKVng+XKWzLCNn7pTTSLitp5+xa4="
