boost_cpp:
- '1.72'
bzip2:
- '1'
c_compiler:
- gcc
c_compiler_version:
- '7'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- gxx
cxx_compiler_version:
- '7'
docker_image:
- condaforge/linux-anvil-comp7
glog:
- 0.4.0
grpc_cpp:
- '1.27'
libprotobuf:
- '3.11'
lz4_c:
- 1.8.3
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  grpc-cpp:
    max_pin: x.x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
  zstd:
    max_pin: x.x.x
python:
- '3.8'
snappy:
- '1'
zlib:
- '1.2'
zstd:
- 1.4.4
