boost_cpp:
- 1.70.0
c_compiler:
- gcc
c_compiler_version:
- '7'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- gxx
cxx_compiler_version:
- '7'
docker_image:
- condaforge/linux-anvil-comp7
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
python:
- '3.6'
