aws_sdk_cpp:
- 1.8.151
bzip2:
- '1'
c_compiler:
- gcc
c_compiler_version:
- '9'
cdt_name:
- cos6
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cuda_compiler:
- nvcc
cuda_compiler_version:
- None
cxx_compiler:
- gxx
cxx_compiler_version:
- '9'
docker_image:
- quay.io/condaforge/linux-anvil-comp7
gflags:
- '2.2'
glog:
- 0.4.0
grpc_cpp:
- '1.36'
libprotobuf:
- '3.15'
lz4_c:
- 1.9.3
numpy:
- '1.17'
orc:
- 1.6.7
pin_run_as_build:
  bzip2:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
python:
- 3.7.* *_cpython
re2:
- 2021.04.01
snappy:
- '1'
target_platform:
- linux-64
thrift_cpp:
- 0.14.1
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - cuda_compiler_version
  - cdt_name
  - docker_image
- - python
  - numpy
zlib:
- '1.2'
zstd:
- '1.4'
