BUILD:
- aarch64-conda_cos7-linux-gnu
aws_sdk_cpp:
- 1.8.63
boost_cpp:
- 1.74.0
bzip2:
- '1'
c_compiler:
- gcc
c_compiler_version:
- '7'
cdt_arch:
- aarch64
cdt_name:
- cos7
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler_version:
- None
cxx_compiler:
- gxx
cxx_compiler_version:
- '7'
docker_image:
- condaforge/linux-anvil-aarch64
gflags:
- '2.2'
glog:
- 0.4.0
grpc_cpp:
- '1.32'
libprotobuf:
- '3.13'
lz4_c:
- 1.9.2
numpy:
- '1.19'
orc:
- 1.6.5
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
python:
- 3.9.* *_cpython
re2:
- 2020.10.01
snappy:
- '1'
target_platform:
- linux-aarch64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - numpy
  - python
zlib:
- '1.2'
zstd:
- '1.4'
