MACOSX_DEPLOYMENT_TARGET:
- '10.9'
boost_cpp:
- 1.70.0
c_compiler:
- clang
c_compiler_version:
- '4'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- clangxx
cxx_compiler_version:
- '4'
macos_machine:
- x86_64-apple-darwin13.4.0
macos_min_version:
- '10.9'
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
python:
- '2.7'
