MACOSX_DEPLOYMENT_TARGET:
- '11.0'
aws_crt_cpp:
- 0.19.8
aws_sdk_cpp:
- 1.10.57
bzip2:
- '1'
c_ares:
- '1'
c_compiler:
- clang
c_compiler_version:
- '14'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler_version:
- None
cxx_compiler:
- clangxx
cxx_compiler_version:
- '14'
gflags:
- '2.2'
glog:
- '0.6'
google_cloud_cpp:
- 2.8.0
libabseil:
- '20230125'
libgrpc:
- '1.52'
libprotobuf:
- '3.21'
lz4_c:
- 1.9.3
macos_machine:
- arm64-apple-darwin20.0.0
numpy:
- '1.21'
- '1.23'
- '1.20'
- '1.20'
openssl:
- '3'
orc:
- 1.8.3
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.10.* *_cpython
- 3.11.* *_cpython
- 3.8.* *_cpython
- 3.9.* *_cpython
re2:
- 2023.02.02
snappy:
- '1'
target_platform:
- osx-arm64
thrift_cpp:
- 0.18.1
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - python
  - numpy
zlib:
- '1.2'
zstd:
- '1.5'
