MACOSX_DEPLOYMENT_TARGET:
- '10.9'
aws_crt_cpp:
- 0.20.3
aws_sdk_cpp:
- 1.10.57
bzip2:
- '1'
c_compiler:
- clang
c_compiler_version:
- '15'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler_version:
- None
cxx_compiler:
- clangxx
cxx_compiler_version:
- '15'
gflags:
- '2.2'
glog:
- '0.6'
google_cloud_cpp:
- '2.12'
libabseil:
- '20230125'
libgrpc:
- '1.54'
- '1.56'
libprotobuf:
- '3.21'
- 4.23.3
lz4_c:
- 1.9.3
macos_machine:
- x86_64-apple-darwin13.4.0
numpy:
- '1.21'
- '1.23'
- '1.21'
- '1.21'
openssl:
- '3'
orc:
- 1.9.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.10.* *_cpython
- 3.11.* *_cpython
- 3.8.* *_cpython
- 3.9.* *_cpython
re2:
- 2023.03.02
snappy:
- '1'
target_platform:
- osx-64
thrift_cpp:
- 0.18.1
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - libgrpc
  - libprotobuf
- - python
  - numpy
zlib:
- '1.2'
zstd:
- '1.5'
