bzip2:
- '1'
c_compiler:
- vs2019
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler:
- nvcc
cuda_compiler_version:
- None
cxx_compiler:
- vs2019
gflags:
- '2.2'
glog:
- '0.5'
google_cloud_cpp:
- '1.35'
grpc_cpp:
- '1.43'
libprotobuf:
- '3.19'
lz4_c:
- 1.9.3
numpy:
- '1.18'
openssl:
- 1.1.1
pin_run_as_build:
  bzip2:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
python:
- 3.7.* *_cpython
re2:
- 2022.02.01
snappy:
- '1'
target_platform:
- win-64
thrift_cpp:
- 0.15.0
zip_keys:
- - python
  - numpy
zlib:
- '1.2'
zstd:
- '1.5'
