aws_sdk_cpp:
- 1.8.54
boost_cpp:
- 1.74.0
bzip2:
- '1'
c_compiler:
- vs2017
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cuda_compiler_version:
- None
cxx_compiler:
- vs2017
gflags:
- '2.2'
glog:
- 0.4.0
grpc_cpp:
- '1.30'
libprotobuf:
- '3.13'
lz4_c:
- 1.9.2
numpy:
- '1.16'
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
python:
- 3.8.* *_cpython
re2:
- 2020.08.01
snappy:
- '1'
target_platform:
- win-64
zlib:
- '1.2'
zstd:
- '1.4'
