CMAKE_GENERATOR:
- NMake Makefiles
boost_cpp:
- 1.70.0
c_compiler:
- vs2015
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- vs2015
glog:
- 0.4.0
libprotobuf:
- '3.8'
lz4_c:
- 1.8.3
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  libprotobuf:
    max_pin: x.x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  snappy:
    max_pin: x.x.x
  vc:
    max_pin: x
  zlib:
    max_pin: x.x
  zstd:
    max_pin: x.x.x
python:
- '3.7'
snappy:
- 1.1.7
vc:
- '14'
zip_keys:
- - python
  - vc
  - c_compiler
  - cxx_compiler
zlib:
- '1.2'
zstd:
- 1.4.0
