# CircleCI configuration file
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - checkout
      - run: |
          git tag circle-$CIRCLE_BUILD_NUM
          git push origin --tags
          cd /root/project/java
          mvn install -DskipTests -Dcheckstyle.skip -Drat.skip=true -pl :flight-jdbc-driver -am
          mkdir -p /root/project/artifacts
      - persist_to_workspace:
          root: /root
          paths:
            - project/
            - .m2/

  maven_deploy:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - attach_workspace:
          at: /root
      - run: |
          mkdir -p /root/.m2
          echo '<settings><servers><server><id>${repo.id}</id><username>${repo.login}</username><password>${repo.pwd}</password></server></servers></settings>' > /root/.m2/settings.xml
          cd /root/project/java/flight/flight-jdbc-driver
          mvn deploy -DskipTests -Drat.skip=true -Dcheckstyle.skip -DaltDeploymentRepository="snapshots::default::$ARTIFACTORY_URL" -e -Drepo.id=snapshots -Drepo.login=$ARTIFACTORY_USER -Drepo.pwd="$ARTIFACTORY_API_KEY" -Dmaven.install.skip=true 

  docker_deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /root
      - run: |
          cd /root/project/java/flight/flight-jdbc-driver
          docker build -f sqlline.Dockerfile . -t spaceandtime.jfrog.io/sxt-docker-docker/ballista-sqlline:$CIRCLE_BUILD_NUM
          docker login -u$ARTIFACTORY_USER -p$ARTIFACTORY_API_KEY spaceandtime.jfrog.io
          docker push spaceandtime.jfrog.io/sxt-docker-docker/ballista-sqlline:$CIRCLE_BUILD_NUM

workflows:
  main_workflow:
    jobs:
      - build
      - maven_deploy:
          requires: 
            - build
      - docker_deploy:
          requires: 
            - build
