# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

os: linux
dist: xenial
language: ruby

# don't build twice
if: tag IS blank

services:
  - docker

addons:
  apt:
    packages:
      - qemu-user-static
      - unar

env:
  global:
    - TRAVIS_TAG={{ task.tag }}
    - BUILD_REF={{ arrow.head }}
    - ARROW_VERSION={{ arrow.version }}

before_script:
  - git clone --no-checkout {{ arrow.remote }} arrow
  - git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
  - git -C arrow checkout {{ arrow.head }}

script:
  - pushd arrow/dev/tasks/linux-packages
  - rake version:update
  - rake dist
  # We can remove this with binfmt-support 2.1.7 or later and
  # qemu-user-static 2.12 or later. It requires Debian buster or later,
  # or Ubuntu 18.10 or later.
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_3.1+dfsg-2ubuntu5_amd64.deb
  - unar *.deb
  - rm *.deb
  - pushd qemu-user-static*
  - unar data.*
  - cp data/usr/bin/qemu-aarch64-static ../apt/debian-stretch-arm64/
  - popd
  - {{ build_command }}

deploy:
  provider: releases
  api_key: $CROSSBOW_GITHUB_TOKEN
  file_glob: true
  file:
  {% for extension in upload_extensions -%}
    - "**/*{{ extension }}"
  {% endfor -%}
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    - {{ job.email }}
