package:
  name: pyarrow
  version: {{ ARROW_VERSION }}

source:
  path: ../../../../

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - arrow-cpp {{ ARROW_VERSION }}
    - boost-cpp
    - cython
    - numpy 1.14.*
    - python
    - setuptools
    - setuptools_scm
    - six

  run:
    - {{ pin_compatible('arrow-cpp') }}
    - {{ pin_compatible('numpy', lower_bound='1.14') }}
    - boost-cpp
    - futures  # [py==27]
    - glog
    - pandas
    # empty parquet-cpp metapackage, force old versions to be uninstalled
    - parquet-cpp 1.5.1.*
    - python
    - six
    - snappy

test:
  imports:
    - pyarrow
    - pyarrow.flight   # [not py==27]
    - pyarrow.gandiva  # [not py==27]
    - pyarrow.orc      # [unix]
    - pyarrow.parquet
    - pyarrow.plasma   # [unix]

  requires:
    - pytest
    - hypothesis

  commands:
    - pytest -m "not requires_testing_data" --pyargs pyarrow

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
