c_compiler:
- gcc
c_compiler_version:
- '7'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- gxx
cxx_compiler_version:
- '7'
docker_image:
- condaforge/linux-anvil-comp7
pin_run_as_build:
  r-base:
    min_pin: x.x
    max_pin: x.x
r_base:
- '3.6'
target_platform:
- linux-64
