BUILD:
- aarch64-conda_cos7-linux-gnu
c_compiler:
- gcc
c_compiler_version:
- '11'
cdt_arch:
- aarch64
cdt_name:
- cos7
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cxx_compiler:
- gxx
cxx_compiler_version:
- '11'
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
pin_run_as_build:
  r-base:
    min_pin: x.x
    max_pin: x.x
r_base:
- '4.1'
target_platform:
- linux-aarch64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
