MACOSX_DEPLOYMENT_TARGET:
- '11.0'
c_compiler:
- clang
c_compiler_version:
- '14'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cxx_compiler:
- clangxx
cxx_compiler_version:
- '14'
macos_machine:
- arm64-apple-darwin20.0.0
pin_run_as_build:
  r-base:
    min_pin: x.x
    max_pin: x.x
r_base:
- '4.2'
target_platform:
- osx-arm64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
