MACOSX_DEPLOYMENT_TARGET:
- '10.9'
c_compiler:
- clang
c_compiler_version:
- '10'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- clangxx
cxx_compiler_version:
- '10'
macos_machine:
- x86_64-apple-darwin13.4.0
macos_min_version:
- '10.9'
pin_run_as_build:
  r-base:
    min_pin: x.x
    max_pin: x.x
r_base:
- '3.6'
target_platform:
- osx-64
