# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        Arrow.jl
#repo_url:         https://github.com/USER_NAME/PACKAGE_NAME.jl
#site_description: Description...
#site_author:      USER_NAME

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
