# NOTE: In constrast to the conda-forge recipe, ARROW_VERSION is a templated variable here.
{% set version = ARROW_VERSION %}
{% set cuda_enabled = cuda_compiler_version != "None" %}
{% set build_ext_version = ARROW_VERSION %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}
{% set proc_build_number = "0" %}
{% set llvm_version = "14" %}

package:
  name: apache-arrow
  version: {{ version }}

source:
  path: ../../../../

build:
  number: 0
  # for cuda support, building with one version is enough to be compatible with
  # all later versions, since arrow is only using libcuda, and not libcudart.
  skip: true  # [cuda_compiler_version not in ("None", cuda_compiler_version_min)]
  # temporary: skip CUDA on aarch/ppc until cross-compilation works, see
  # https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/210
  skip: true  # [(aarch64 or ppc64le) and (cuda_compiler_version != "None")]
  run_exports:
    - {{ pin_subpackage("libarrow", max_pin="x.x.x") }}

outputs:
  - name: apache-arrow-proc
    version: {{ build_ext_version }}
    build:
      number: {{ proc_build_number }}
      string: {{ build_ext }}
      ignore_run_exports_from:
        - openssl
    requirements:
      host:
        # ensure we split the CI jobs per openssl version
        - openssl
    test:
      commands:
        - exit 0
    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file:
        - LICENSE.txt
      summary: A meta-package to select Arrow build variant

  # compat output for old mutex-package naming
  - name: arrow-cpp-proc
    version: {{ build_ext_version }}
    build:
      number: {{ proc_build_number }}
      string: {{ build_ext }}
      ignore_run_exports_from:
        - openssl
    requirements:
      host:
        # ensure we split the CI jobs per openssl version
        - openssl
      run:
        - apache-arrow-proc ={{ build_ext_version }}={{ build_ext }}
    test:
      commands:
        - exit 0

  - name: libarrow
    script: build-arrow.sh  # [not win]
    script: bld-arrow.bat   # [win]
    version: {{ version }}
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
      run_exports:
        - {{ pin_subpackage("libarrow", max_pin="x.x.x") }}
      ignore_run_exports:
        - cudatoolkit
      track_features: {{ "[arrow-cuda]" if cuda_enabled else "" }}
      missing_dso_whitelist:
        - "*/libcuda.so.*"    # [linux]
        - "*/nvcuda.dll"      # [win]
    requirements:
      build:
        - clangdev {{ llvm_version }}            # [osx and arm64]
        - llvmdev {{ llvm_version }}             # [osx and arm64]
        - gnuconfig                              # [osx and arm64]
        - libgrpc
        - libprotobuf
        - cmake
        - autoconf  # [unix]
        - ninja
        - make  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
      host:
        - clangdev {{ llvm_version }}
        - llvmdev {{ llvm_version }}
        - aws-sdk-cpp
        - boost-cpp >=1.70
        - brotli
        - bzip2
        - c-ares
        - gflags
        - glog
        - google-cloud-cpp
        - libabseil
        # since libgoogle-cloud is static on windows, see
        # https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/108,
        # its dependencies leak into the build here
        - libcrc32c  # [win]
        - libcurl    # [win]
        - libgrpc
        - libprotobuf
        - libutf8proc
        - lz4-c
        # gandiva depends on openssl
        - openssl
        - orc          # [unix]
        - rapidjson
        - re2
        - snappy
        - thrift-cpp
        - xsimd
        - zlib
        - zstd
      run_constrained:
        - apache-arrow-proc =*={{ build_ext }}
        - cudatoolkit >={{ cuda_compiler_version_min }}  # [cuda_compiler_version != "None"]
        # make sure we don't co-install with old version of old package name
        - arrow-cpp ={{ version }}

    test:
      commands:
        {% set headers = [
            "arrow/api.h", "arrow/flight/types.h", "arrow/flight/sql/api.h",
            "gandiva/engine.h", "parquet/api/reader.h"
        ] %}
        {% set headers = headers + ["plasma/client.h"] %}  # [unix]
        {% for each_header in headers %}
        # headers
        - test -f $PREFIX/include/{{ each_header }} || (echo "{{ each_header }} not found" && exit 1)  # [unix]
        - if not exist %LIBRARY_INC%\{{ "\\".join(each_header.split("/")) }} exit 1                    # [win]
        {% endfor %}

        {% set libs = (cuda_compiler_version != "None") * ["arrow_cuda"] + [
            "arrow", "arrow_dataset", "arrow_flight", "arrow_flight_sql",
            "arrow_substrait", "gandiva", "parquet"
        ] %}
        {% set libs = libs + ["plasma"] %}  # [unix]
        {% for each_lib in libs %}
        # shared
        - test -f $PREFIX/lib/lib{{ each_lib }}.so                 # [linux]
        - test -f $PREFIX/lib/lib{{ each_lib }}.dylib              # [osx]
        - if not exist %LIBRARY_BIN%\{{ each_lib }}.dll exit 1     # [win]
        - if not exist %LIBRARY_LIB%\{{ each_lib }}.lib exit 1     # [win]

        # absence of static libraries
        - test ! -f $PREFIX/lib/lib{{ each_lib }}.a                # [unix]
        - if exist %LIBRARY_LIB%\{{ each_lib }}_static.lib exit 1  # [win]
        {% endfor %}

        # absence of arrow_cuda for CPU builds
        - test ! -f $PREFIX/lib/libarrow_cuda.so                   # [(cuda_compiler_version == "None") and linux]
        - test ! -f $PREFIX/lib/libarrow_cuda.a                    # [(cuda_compiler_version == "None") and linux]
        - if exist %LIBRARY_BIN%\arrow_cuda.dll exit 1             # [(cuda_compiler_version == "None") and win]
        - if exist %LIBRARY_LIB%\arrow_cuda.lib exit 1             # [(cuda_compiler_version == "None") and win]
        - if exist %LIBRARY_LIB%\arrow_cuda_static.lib exit 1      # [(cuda_compiler_version == "None") and win]

    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file:
        - LICENSE.txt
      summary: C++ libraries for Apache Arrow

  # compat output for old naming scheme; switched for 10.0.0; keep for a few versions
  - name: arrow-cpp
    version: {{ version }}
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
      run_exports:
        - {{ pin_subpackage("libarrow", max_pin="x.x.x") }}
    requirements:
      host:
        # make sure the builds for different openssl versions (with the same PKG_BUILDNUM) have different hashes
        - openssl
        - {{ pin_subpackage('libarrow', exact=True) }}
      run:
        - {{ pin_subpackage('libarrow', exact=True) }}
    test:
      commands:
        - exit 0

  - name: pyarrow
    script: build-pyarrow.sh  # [not win]
    script: bld-pyarrow.bat   # [win]
    version: {{ version }}
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
      ignore_run_exports:
        - cudatoolkit
      ignore_run_exports_from:
        - openssl
      track_features: {{ "[arrow-cuda]" if cuda_enabled else "" }}
      missing_dso_whitelist:
        # not actually missing, but installed into SP_DIR, see tests
        - "*/libarrow_python.so.*"            # [linux]
        - "*/libarrow_python_flight.so.*"     # [linux]
        - "*/libarrow_python.*.dylib"         # [osx]
        - "*/libarrow_python_flight.*.dylib"  # [osx]
        - "*/arrow_python.dll"                # [win]
        - "*/arrow_python_flight.dll"         # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - cmake
        - ninja
        - make  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # pyarrow does not require nvcc but it needs to link against libraries in libarrow=*=*cuda
        - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
      host:
        - {{ pin_subpackage('libarrow', exact=True) }}
        - clangdev {{ llvm_version }}
        - llvmdev {{ llvm_version }}
        - cython
        - gflags  # [unix]
        - numpy
        - openssl
        - python
        - setuptools
        - setuptools_scm
      run:
        - {{ pin_subpackage('libarrow', exact=True) }}
        - {{ pin_compatible('numpy') }}
        # empty parquet-cpp metapackage, force old versions to be uninstalled
        - parquet-cpp 1.5.1.*
        - python
      run_constrained:
        - apache-arrow-proc =*={{ build_ext }}
        - cudatoolkit >={{ cuda_compiler_version_min }}  # [cuda_compiler_version != "None"]

    test:
      files:
        - test_read_parquet.py
      imports:
        - pyarrow
        - pyarrow.dataset
        - pyarrow.flight
        - pyarrow.gandiva
        - pyarrow.orc      # [unix]
        - pyarrow.parquet
        - pyarrow.plasma   # [unix]
        - pyarrow.fs
        - pyarrow._s3fs
        - pyarrow._hdfs
        # We can only test importing cuda package but cannot run when a
        # CUDA device is not available, for instance, when building from CI.
        # On Windows, we cannot even do that due to `nvcuda.dll` not being found, see
        # https://conda-forge.org/docs/maintainer/knowledge_base.html#nvcuda-dll-cannot-be-found-on-windows
        # However, we check below for (at least) the presence of a correctly-compiled module
        - pyarrow.cuda     # [cuda_compiler_version != "None" and not win]
      commands:
        # libraries that depend on python (and hence aren't in libarrow itself)
        - test -f ${SP_DIR}/pyarrow/libarrow_python.so                            # [linux]
        - test -f ${SP_DIR}/pyarrow/libarrow_python_flight.so                     # [linux]
        - test -f ${SP_DIR}/pyarrow/libarrow_python.dylib                         # [osx]
        - test -f ${SP_DIR}/pyarrow/libarrow_python_flight.dylib                  # [osx]
        - if not exist %SP_DIR%\pyarrow\arrow_python.dll exit 1                   # [win]
        - if not exist %SP_DIR%\pyarrow\arrow_python_flight.dll exit 1            # [win]

        - test -f ${SP_DIR}/pyarrow/include/arrow/python/pyarrow.h                # [unix]
        - if not exist %SP_DIR%\pyarrow\include\arrow\python\pyarrow.h exit 1     # [win]

        - test ! -f ${SP_DIR}/pyarrow/tests/test_array.py                         # [unix]
        - if exist %SP_DIR%/pyarrow/tests/test_array.py exit 1                    # [win]
        # Need to remove dot from PY_VER; %MYVAR:x=y% replaces "x" in %MYVAR% with "y"
        - if not exist %SP_DIR%/pyarrow/_cuda.cp%PY_VER:.=%-win_amd64.pyd exit 1  # [win and cuda_compiler_version != "None"]
        - python test_read_parquet.py

    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file:
        - LICENSE.txt
      summary: Python libraries for Apache Arrow

  - name: pyarrow-tests
    script: build-pyarrow.sh  # [not win]
    script: bld-pyarrow.bat   # [win]
    version: {{ version }}
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
      ignore_run_exports:
        - cudatoolkit
      ignore_run_exports_from:
        - openssl
      track_features: {{ "[arrow-cuda]" if cuda_enabled else "" }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - cmake
        - ninja
        - make  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # pyarrow does not require nvcc but it needs to link against libraries in libarrow=*=*cuda
        - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
      host:
        - {{ pin_subpackage('libarrow', exact=True) }}
        - {{ pin_subpackage('pyarrow', exact=True) }}
        - clangdev {{ llvm_version }}
        - llvmdev {{ llvm_version }}
        - cython
        - numpy
        - openssl
        - python
        - setuptools
        - setuptools_scm
      run:
        - {{ pin_subpackage('pyarrow', exact=True) }}
        - python
      run_constrained:
        - apache-arrow-proc =*={{ build_ext }}
        - cudatoolkit >={{ cuda_compiler_version_min }}  # [cuda_compiler_version != "None"]

    test:
      requires:
        - pytest
        - pytest-lazy-fixture
        - backports.zoneinfo  # [py<39]
        - cffi
        - cloudpickle
        - cython
        - fastparquet
        - fsspec
        - hypothesis
        - pandas
        # not all arches available in conda-forge; osx-arm not tested anyway
        - pytorch *           # [unix and not ppc64le and py<311]
        - scipy
        # we're not building java bindings
        # - jpype1
        # doesn't get picked up correctly
        # - libhdfs3
        # causes segfaults
        # - sparse
        # not rebuilt for grpc 1.49 yet
        # - tensorflow
      source_files:
        - testing/data
      commands:
        - cd ${SP_DIR}/pyarrow/tests                        # [unix]
        - cd %SP_DIR%\pyarrow\tests                         # [win]
        - export ARROW_TEST_DATA="${SRC_DIR}/testing/data"  # [unix]
        - set "ARROW_TEST_DATA=%SRC_DIR%\testing\data"      # [win]

        {% set tests_to_skip = "_not_a_real_test" %}
        # we do not have GPUs in CI --> cannot test cuda
        {% set tests_to_skip = tests_to_skip + " or test_cuda" %}
        # skip tests that raise SIGINT and crash the test suite
        {% set tests_to_skip = tests_to_skip + " or (test_csv and test_cancellation)" %}  # [linux]
        {% set tests_to_skip = tests_to_skip + " or (test_flight and test_interrupt)" %}  # [linux]
        # skip tests that make invalid(-for-conda) assumptions about the compilers setup
        {% set tests_to_skip = tests_to_skip + " or test_cython_api" %}                   # [unix]
        {% set tests_to_skip = tests_to_skip + " or test_visit_strings" %}                # [unix]
        # skip tests that cannot succeed in emulation
        {% set tests_to_skip = tests_to_skip + " or test_debug_memory_pool_disabled" %}   # [aarch64 or ppc64le]
        {% set tests_to_skip = tests_to_skip + " or test_env_var_io_thread_count" %}      # [aarch64 or ppc64le]
        # vvvvvvv TESTS THAT SHOULDN'T HAVE TO BE SKIPPED vvvvvvv
        # failing on linux with "OSError: Could not connect to socket /tmp/[...]/plasma.sock"
        {% set tests_to_skip = tests_to_skip + " or test_plasma" %}                       # [linux]
        # "Unsupported backend 'nonexistent' specified in ARROW_DEFAULT_MEMORY_POOL"
        {% set tests_to_skip = tests_to_skip + " or (test_memory and test_env_var)" %}    # [unix]
        # test is broken; header is in $PREFIX, not $SP_DIR
        {% set tests_to_skip = tests_to_skip + " or (test_misc and test_get_include)" %}  # [unix]
        # ^^^^^^^ TESTS THAT SHOULDN'T HAVE TO BE SKIPPED ^^^^^^^

        # crossbow CI: reduce to one python version, except on (unemulated) linux, where it's fast enough
        - pytest -v -rfEs -k "not ({{ tests_to_skip }})"  # [linux64 or ((py==310) and not ppc64le)]
        # NOTE: test suite is skipped on ppc due to bugs in QEMU code that cause
        # CI to fail, even though the tests would run through on native hardware

    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file:
        - LICENSE.txt
      summary: Python test files for Apache Arrow

about:
  home: http://github.com/apache/arrow
  license: Apache-2.0
  license_file:
    - LICENSE.txt
  summary: C++ and Python libraries for Apache Arrow

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
    - pearu
    - nealrichardson
    - jakirkham
    - h-vetinari
  feedstock-name: arrow-cpp
