boost_cpp:
- 1.68.0
build_number_decrement:
- '1000'
c_compiler:
- toolchain_c
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- toolchain_cxx
docker_image:
- condaforge/linux-anvil
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
python:
- '3.6'
zip_keys:
- - c_compiler
  - cxx_compiler
  - channel_sources
  - channel_targets
  - docker_image
  - build_number_decrement
