boost_cpp:
- 1.68.0
c_compiler:
- vs2015
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- vs2015
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
python:
- '3.7'
zip_keys:
- - python
  - c_compiler
  - cxx_compiler
