environment:
  ARROW_VERSION: {{ arrow.no_rc_version }}
  # regardless of the python version we build against
  CONDA_INSTALL_LOCN: C:\Miniconda36-x64

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
  - x64

install:
  # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
  - cmd: rmdir C:\cygwin /s /q

  # Add path, activate `conda` and update conda.
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda

  - cmd: set PYTHONUNBUFFERED=1

  # Configure the VM.
  - cmd: conda.exe install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build

# Skip .NET project specific build phase.
build: off

test_script:
  # Clone arrow
  - git clone --no-checkout {{ arrow.remote }} arrow || exit /B
  - git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }} || exit /B
  - git -C arrow checkout FETCH_HEAD || exit /B

  - pushd arrow\dev\tasks\conda-recipes

  # Configure conda
  - cmd: setup_conda_rc .\ .\ .ci_support\{{ config }}.yaml
  - cmd: run_conda_forge_build_setup

  # Build the recipes
  - conda.exe build --output-folder . -m .ci_support\{{ config }}.yaml parquet-cpp arrow-cpp pyarrow

  # Rename artifacts
  - pushd win-64
  - for %%f in (*.tar.bz2) do (
      set %%g=%%~nf
      ren "%%f" "%%~ng-win-64.tar.bz2"
    )

artifacts:
  # this must be relative and child of the build C:\projects\crossbow directory
  - path: arrow\dev\tasks\conda-recipes\win-64\*.tar.bz2

deploy:
  release: {{ task.tag }}
  provider: GitHub
  auth_token: "%CROSSBOW_GITHUB_TOKEN%"
  artifact: /.*\.tar\.bz2/
  draft: false
  prerelease: false
  force_update: true

notifications:
  - provider: Email
    to:
      - {{ job.email }}
