jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360

  variables:
    CONFIG: {{ config }}
    ARROW_VERSION: {{ arrow.no_rc_version }}
    DOCKER_IMAGE: condaforge/linux-anvil-comp7
    UPLOAD_PACKAGES: False

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    displayName: Configure binfmt_misc
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))

  - script: |
      git clone --no-checkout {{ arrow.remote }} arrow
      git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
      git -C arrow checkout FETCH_HEAD
    displayName: Clone arrow

  - script: CI=azure ./run_docker_build.sh
    displayName: Run docker build
    workingDirectory: arrow/dev/tasks/conda-recipes

  # Using github release tries to find a common ancestor between the currently
  # pushed tag and the latest tag of the github repository (don't know why).
  # The tag upload took 43 minutes because of this scan, so use an alternative
  # upload script.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      python -m pip install github3-py click
      python upload-assets.py \
        --sha {{ task.branch }} \
        --tag {{ task.tag }} \
        --pattern "conda-recipes/build_artifacts/linux-64/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_REPO: $(Build.Repository.Name)
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release
    workingDirectory: arrow/dev/tasks
