[package]
name = "ballista-executor"
description = "Ballista Distributed Compute - Executor"
license = "Apache-2.0"
version = "0.4.2-SNAPSHOT"
homepage = "https://github.com/ballista-compute/ballista"
repository = "https://github.com/ballista-compute/ballista"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

[features]
default = ["snmalloc"]
snmalloc = ["snmalloc-rs"]

[dependencies]
anyhow = "1"
async-trait = "0.1.36"
ballista-core = { path = "../core" }
ballista-scheduler = { path = "../scheduler" }
configure_me = "0.4.0"
env_logger = "0.8"
futures = "0.3"
log = "0.4"
snmalloc-rs = {version = "0.2", features= ["cache-friendly"], optional = true}
tempfile = "3"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }
tokio-stream = "0.1"
tonic = "0.4"
uuid = { version = "0.8", features = ["v4"] }

arrow = { git = "https://github.com/apache/arrow", rev="46161d2" }
arrow-flight = { git = "https://github.com/apache/arrow", rev="46161d2" }
datafusion = { git = "https://github.com/apache/arrow", rev="46161d2" }

[dev-dependencies]

[build-dependencies]
configure_me_codegen = "0.4.0"

[package.metadata.configure_me.bin]
executor = "executor_config_spec.toml"

