# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Check Labels Reusable

on:
  workflow_call:
    inputs:
      parent-workflow:
        description: "The parent workflow filename (without .yml)"
        required: true
        type: string
    outputs:
      ci-extra-labels:
        description: "The extra CI labels"
        value: ${{ jobs.check-labels.outputs.ci-extra-labels }}
      force:
        description: "Whether to force running the jobs"
        value: ${{ jobs.check-labels.outputs.force }}

jobs:
  check-labels:
    name: Check labels
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      ci-extra-labels: ${{ steps.check.outputs.ci-extra-labels }}
      force: ${{ steps.check.outputs.force }}
    steps:
      - name: Checkout Arrow
        if: github.event_name == 'pull_request'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -ex
          case "${GITHUB_EVENT_NAME}" in
            push|schedule|workflow_dispatch)
              echo "force=true" >> "${GITHUB_OUTPUT}"
              ;;
            pull_request)
              {
                echo "ci-extra-labels<<LABELS"
                gh pr view ${{ github.event.number }} \
                  --jq '[.labels[].name | select(startswith("CI: Extra"))]' \
                  --json labels \
                  --repo ${GITHUB_REPOSITORY}
                echo "LABELS"
              } >> "${GITHUB_OUTPUT}"
              git fetch origin ${GITHUB_BASE_REF}
              git diff --stat origin/${GITHUB_BASE_REF}..
              if git diff --stat origin/${GITHUB_BASE_REF}.. | \
                   grep \
                     --fixed-strings ".github/workflows/${{ inputs.parent-workflow }}.yml" \
                     --quiet; then
                echo "force=true" >> "${GITHUB_OUTPUT}"
              fi
              ;;
          esac
