# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Java

on:
  push:
    paths:
      - '.github/workflows/java.yml'
      - 'ci/docker/*java*'
      - 'ci/scripts/java*.sh'
      - 'ci/scripts/util_*.sh'
      - 'format/Flight.proto'
      - 'java/**'
  pull_request:
    paths:
      - '.github/workflows/java.yml'
      - 'ci/docker/*java*'
      - 'ci/scripts/java*.sh'
      - 'ci/scripts/util_*.sh'
      - 'format/Flight.proto'
      - 'java/**'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  DOCKER_VOLUME_PREFIX: ".docker/"
  ARCHERY_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
  ARCHERY_DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:

  debian:
    name: ${{ matrix.title }}
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        jdk: [8, 11, 17, 18]
        include:
        - jdk: 8
          title: AMD64 Debian 9 Java JDK 8 Maven 3.5.4
          maven: 3.5.4
          image: debian-java
        - jdk: 11
          title: AMD64 Debian 9 Java JDK 11 Maven 3.6.2
          maven: 3.6.2
          image: debian-java
        - jdk: 17
          title: AMD64 Oracle Linux Server 8.5 Java JDK 17 Maven 3.8.5
          maven: 3.8.5
          image: oracle-java
        - jdk: 18
          title: AMD64 Oracle Linux Server 8.6 Java JDK 18 Maven 3.8.5
          maven: 3.8.5
          image: oracle-java
    env:
      JDK: ${{ matrix.jdk }}
      MAVEN: ${{ matrix.maven }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Cache Docker Volumes
        uses: actions/cache@v2
        with:
          path: .docker
          key: maven-${{ hashFiles('java/**') }}
          restore-keys: maven-
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup Archery
        run: pip install -e dev/archery[docker]
      - name: Execute Docker Build
        run: archery docker run ${{ matrix.image }}
      - name: Docker Push
        if: success() && github.event_name == 'push' && github.repository == 'apache/arrow'
        continue-on-error: true
        run: archery docker push ${{ matrix.image }}

  macos:
    name: AMD64 MacOS 10.15 Java JDK ${{ matrix.jdk }}
    runs-on: macos-latest
    if: github.event_name == 'push'
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        jdk: [11]
    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Checkout Arrow
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        shell: bash
        run: ci/scripts/java_build.sh $(pwd) $(pwd)/build
      - name: Test
        shell: bash
        run: ci/scripts/java_test.sh $(pwd) $(pwd)/build
